services:
    fenrizbes_yandex_maps.form.type.yandex_maps:
        class: Fenrizbes\YandexMapsFormTypeBundle\Form\Type\YandexMapsType
        arguments:
            - %fenrizbes_yamap.size%
            - %fenrizbes_yamap.default%
            - %fenrizbes_yamap.parameters%
        tags:
            - { name: form.type, alias: yandex_maps }
